export default function Head() {
    return (
        <>
        <title>FInance Tracker</title>
        <meta content="width=device-width, initial-scale=1" name=""/>
        <meta name= "description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        </>
    )
}